#!/usr/bin/env python
# coding: utf-8

'''
Compare the local LVM master-calibration cache against what is available
remotely at Utah, and generate a reviewable command file that removes
local MJD folders no longer present remotely and then re-runs
`drp get-calibs` to pick up anything new or updated.

Usage::

    lvm_cal_sync.py [-h] [-out FILE]

Options::

    -out FILE   name of the generated command file (default:
                SyncCalCommands.<YYMMDD>.txt)

Description:

`drp get-calibs` downloads master calibration frames from the Utah SAS
into the local calibration cache ($LVM_MASTER_DIR, i.e. sdss_access's
'lvm_calib' path template -- typically $LVM_SANDBOX/calib). It runs in
rsync mode without --delete, so a local MJD folder that is no longer
present remotely (e.g. a superseded/retagged calibration epoch) is never
cleaned up and will persist indefinitely.

This matters because lvmdrp's get_master_mjd() (python/lvmdrp/utils/paths.py)
picks a calibration set purely by listing local MJD folders and taking the
latest one <= the science MJD -- it never checks whether that MJD is still
the best/valid one upstream. A stale local MJD folder can silently become
the one reductions use, with no warning in the logs.

This script never deletes anything and never runs get-calibs itself. It
only::

    1. Lists local MJD folders under the calibration cache. Any subfolder
       whose name is not purely digits (e.g. pixelmasks, stellar_models) is a
       special non-MJD folder that get-calibs manages separately, and is
       never treated as a removal candidate here.
    2. Lists remote MJD folders available at Utah for lvm_calib (kind=*,
       camera=*), via sdss_access -- a read-only listing (Access.set_stream()
       without .commit()), so nothing is downloaded.
    3. Diffs the two sets and writes the command file, containing:
       - a `rm -r` command for every local-only (stale) MJD
       - a comment noting every remote-only (new) MJD, for visibility
       - a single `drp get-calibs` line at the end to fetch anything new or
         updated
    4. Prints a summary of what will be removed/added to the screen.

Nothing in the generated file is executed automatically -- review it,
then run it yourself, e.g. `bash SyncCalCommands.260714.txt`.

History:

    260714 ksl Coding begun.
'''

import sys
import os
import re
import time
from sdss_access import Access


def _usage_from_doc(doc):
    '''
    __doc__ truncated just before a line consisting of "History:"
    (whitespace-insensitive), so -h stays short even as that section
    grows -- without hand-duplicating the Synopsis/Options text in a
    second string.  Anchored to a whole line (not a bare substring
    search) so it can't misfire on "History:" appearing mid-sentence,
    and returns doc unchanged if no such line is present.
    '''
    m = re.search(r'^\s*History:\s*$', doc, re.MULTILINE)
    return doc[:m.start()].rstrip() + '\n' if m else doc


_USAGE = _usage_from_doc(__doc__)


_MJD_RE = re.compile(r'^\d+$')


def get_remote_mjds(kind='*', camera='*'):
    '''
    Read-only: lists MJD folders available remotely at Utah for lvm_calib,
    without downloading anything. Access.set_stream() alone resolves the
    listing (an rsync dry-run under the hood); only a subsequent .commit()
    would actually transfer files, and this never calls .commit().

    Returns (mjds, access) -- the Access instance is returned too so its
    path-template resolution (.full()) can be reused to locate the local
    calib directory.
    '''
    a = Access()
    a.remote()
    a.add('lvm_calib', kind=kind, mjd='*', camera=camera)
    a.set_stream()

    mjds = set()
    for task in a.stream.task:
        m = re.search(r'/calib/(\d+)/', task['location'])
        if m:
            mjds.add(m.group(1))
    return mjds, a


def get_local_mjds(a):
    '''
    Local MJD folders under the same calib directory get-calibs writes to,
    resolved via the same sdss_access path template so this automatically
    respects LVM_MASTER_DIR / $LVM_SANDBOX rather than a hardcoded path.
    '''
    sample = a.full('lvm_calib', kind='bias', mjd='00000', camera='b1')
    calib_dir = os.path.dirname(os.path.dirname(sample))

    entries = os.listdir(calib_dir) if os.path.isdir(calib_dir) else []
    mjds = {d for d in entries
            if _MJD_RE.match(d) and os.path.isdir(os.path.join(calib_dir, d))}
    return calib_dir, mjds


def write_command_file(outfile, calib_dir, stale, new):
    '''Writes the reviewable rm -r / get-calibs command file. Nothing here is executed.'''
    with open(outfile, 'w') as f:
        f.write('# Generated by lvm_cal_sync.py on %s\n' % time.strftime('%Y-%m-%d %H:%M:%S'))
        f.write('# Review before running -- nothing here has been executed.\n')
        f.write('#\n')
        f.write('# Local calib directory: %s\n' % calib_dir)
        f.write('# %d local MJD(s) absent remotely -- removal candidates\n' % len(stale))
        f.write('# %d remote MJD(s) not yet local -- get-calibs will fetch these\n' % len(new))
        f.write('\n')

        if stale:
            f.write('# --- Stale local MJDs (no longer present at Utah) ---\n')
            for mjd in stale:
                f.write('rm -r %s\n' % os.path.join(calib_dir, mjd))
            f.write('\n')
        else:
            f.write('# No stale local MJDs found.\n\n')

        if new:
            f.write('# --- New remote MJDs (fetched below by get-calibs) ---\n')
            for mjd in new:
                f.write('# will add MJD %s (via get-calibs)\n' % mjd)
            f.write('\n')

        f.write('# --- Resync everything (adds new/updated, no -m filter) ---\n')
        f.write('drp get-calibs\n')


def steer(argv):
    outfile = ''

    i = 1
    while i < len(argv):
        if argv[i] == '-h':
            print(_USAGE)
            return
        elif argv[i] == '-out':
            i += 1
            outfile = argv[i]
        elif argv[i].startswith('-'):
            print('Error: unknown option "%s"' % argv[i])
            print(_USAGE)
            return
        else:
            print('Error: unexpected argument "%s"' % argv[i])
            print(_USAGE)
            return
        i += 1

    if not outfile:
        outfile = 'SyncCalCommands.%s.txt' % time.strftime('%y%m%d')

    print('Querying remote calibration listing at Utah (read-only, no download)...')
    remote_mjds, a = get_remote_mjds()
    calib_dir, local_mjds = get_local_mjds(a)

    stale = sorted(local_mjds - remote_mjds)
    new = sorted(remote_mjds - local_mjds)

    print('Local calib directory: %s' % calib_dir)
    print('Local MJDs: %d   Remote MJDs: %d' % (len(local_mjds), len(remote_mjds)))
    print()
    print('%d local MJD folder(s) no longer present remotely (will be marked for removal):' % len(stale))
    for mjd in stale:
        print('    %s' % mjd)
    print()
    print('%d remote MJD folder(s) not yet local (get-calibs will fetch these):' % len(new))
    for mjd in new:
        print('    %s' % mjd)

    write_command_file(outfile, calib_dir, stale, new)

    print('\nWrote %s' % outfile)
    print('Review it, then run it yourself, e.g.: bash %s' % outfile)


if __name__ == '__main__':
    if '-h' in sys.argv or '--help' in sys.argv:
        print(_USAGE)
    else:
        steer(sys.argv)
